import { QuietProfile, TransmitterOptions } from "./interfaces";
import { EventEmitter } from "eventemitter3";
export declare class Transmitter extends EventEmitter {
    profileObj: QuietProfile;
    done: () => void;
    clampFrame: boolean;
    opt: string;
    c_profiles: number[];
    c_profile: number[];
    private encoder;
    private quiet;
    running: boolean;
    inited: boolean;
    private sample_view;
    private samplesToPlay;
    private emptySample;
    private payload;
    private opts;
    private samples;
    private last_emit_times;
    private num_emit_times;
    private empties_written;
    private scriptNode;
    private mediaStreamDestination;
    private dummy_osc;
    private frame_len;
    private stream;
    private playing;
    private paused;
    constructor(opts: TransmitterOptions);
    pause(): void;
    resume(): void;
    transmit(buf: ArrayBuffer): Promise<void>;
    transmitText(text: string): Promise<void>;
    startTransmitter(): void;
    writebuf(): void;
    readBuf(): void;
    stopTransmitter(): void;
}
